#!/usr/bin/env node
// Bundle the 3D view into a single self-contained IIFE that runs as the body of
// Dataview's dv.view() async function (dv/input are host-provided identifiers —
// deliberately left as free variables, never window globals).
import { build } from "esbuild";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
await build({
  entryPoints: [resolve(here, "src/view-entry.js")],
  outfile: resolve(here, "../../views/isds-workflow-3d/view.js"),
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  logLevel: "info",
  banner: { js: "/* GENERATED by tools/isds-workflow-3d/build.mjs — do not hand-edit. */" },
});
console.log("bundled views/isds-workflow-3d/view.js");
