#!/usr/bin/env node
// Standalone SVG renderer for the professor-facing site + GitHub README.
// Feeds the SAME manifest through chart-core.buildChart with a string-based
// element factory — no DOM, no browser — and writes ONE self-contained file:
//   scripts/site_templates/assets/workflow.svg
//
// Design decisions (deliberate):
// - ONE file, light-first: light colors ride as presentation attributes (they
//   render even where CSS is ignored); the dark theme is an internal
//   @media (prefers-color-scheme: dark) override. Because the chart paints
//   its own background, it stays internally legible in EITHER scheme even
//   when a host (e.g., GitHub's manual theme toggle) disagrees with the OS.
// - SMIL animateMotion dots are preserved — they animate inside <img> embeds.
// - <title> tooltips are preserved; click-through is vault-only by design.
// - prefers-reduced-motion hides the dots; the arrows carry the full story.
// - Freshness guard: the sha256 of (workflow.json bytes + render-config.mjs
//   bytes, in that order) is embedded as a comment; validate.mjs recomputes it
//   and FAILS the build when the committed SVG is stale.
// Deterministic: a second run over identical inputs is byte-identical.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import * as config from "./src/render-config.mjs";
import { buildChart, flattenTheme } from "./src/chart-core.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const MANIFEST = resolve(here, "../../views/isds-workflow-3d/workflow.json");
const CONFIG = resolve(here, "src/render-config.mjs");
const OUT = resolve(here, "../../scripts/site_templates/assets/workflow.svg");

// ---- string element factory (chart-core's only view of the world) ----
const makeNode = (name, attrs) => ({ name, attrs: { ...(attrs || {}) }, children: [], text: null });
const factory = {
  el(name, attrs, parent) {
    const n = makeNode(name, attrs);
    if (parent) parent.children.push(n);
    return n;
  },
  setText(node, str) { node.text = String(str); },
};

const ESC = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" };
const escText = (s) => String(s).replace(/[&<>]/g, (c) => ESC[c]);
const escAttr = (s) => String(s).replace(/[&<>"]/g, (c) => ESC[c]);
function serialize(n) {
  const attrs = Object.entries(n.attrs).map(([k, v]) => ` ${k}="${escAttr(v)}"`).join("");
  const inner = (n.text != null ? escText(n.text) : "") + n.children.map(serialize).join("");
  return inner ? `<${n.name}${attrs}>${inner}</${n.name}>` : `<${n.name}${attrs}/>`;
}

// ---- build ----
const manifestBytes = readFileSync(MANIFEST);
const configBytes = readFileSync(CONFIG);
const manifest = JSON.parse(manifestBytes.toString("utf8"));

const { svg, width, height } = buildChart(manifest, config, factory, {
  theme: "light",
  // System stack close to the site's Libre Franklin; webfonts cannot load
  // inside <img> embeds, so we never reference one.
  font: "-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif",
});

// Root attributes: xmlns first (standalone document), explicit pixel size for
// stable <img> layout, role for assistive tech.
svg.attrs = { xmlns: "http://www.w3.org/2000/svg", ...svg.attrs, width, height, role: "img" };

// Accessible name + the theme/motion stylesheet, prepended in that order.
const docTitle = makeNode("title", {});
docTitle.text = manifest.meta.title;
const style = makeNode("style", {});
const dark = flattenTheme(config.THEMES.dark);
style.text =
  "@media (prefers-color-scheme: dark){" +
  Object.entries(dark).map(([t, v]) => `.wf-f-${t}{fill:${v}}.wf-s-${t}{stroke:${v}}`).join("") +
  "}@media (prefers-reduced-motion: reduce){.wf-dot{display:none}}";
svg.children.unshift(style);
svg.children.unshift(docTitle);

// ---- freshness hash + write ----
const inputsSha = createHash("sha256").update(manifestBytes).update(configBytes).digest("hex");
const out =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- GENERATED by tools/isds-workflow-3d/render-static.mjs — do not hand-edit. Re-render: npm run render-static (in tools/isds-workflow-3d). -->\n` +
  `<!-- inputs-sha256: ${inputsSha} (sha256 of views/isds-workflow-3d/workflow.json bytes + src/render-config.mjs bytes, in that order; checked by validate.mjs) -->\n` +
  serialize(svg) + "\n";

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(`wrote scripts/site_templates/assets/workflow.svg (${out.length} bytes, ${width}x${height}, inputs-sha256 ${inputsSha.slice(0, 12)}…)`);
